server:
  port: 8006
spring:
  application:
    name: bxl-consumer
  boot:
    admin:
      client:
        url: "http://localhost:8003"
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8004/eureka
feign:
  hystrix:
    enabled: true
